// packages/web-main/pages/index.tsx
import React from 'react'
import { NextFunctionComponent } from 'next'
import styled from 'styled-components'

const MainContainer = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`

const TitleBox = styled.div`
  width: 100%;
  padding-left: 30px;
  padding-right: 30px;
  display: flex;
  flex-direction: column;
`

const Title = styled.div`
  font-family: OCR-A, monospace;
  font-size: 32px;
`

const Motto = styled.div`
  margin-top: 8px;
  font-size: 16px;
  color: #666;
  letter-spacing: 2px;
`

const Index: NextFunctionComponent = () => {
  return (
    <MainContainer>
      <TitleBox>
        <Title>mingchuan.me</Title>
        <Motto>這個世界的異鄉人</Motto>
      </TitleBox>
    </MainContainer>
  )
}

export default Index

// src/web.mce/pages/index.vue
<template>
  <div class="container">
    <div class="container-h">
      <div class="logo">mingchuan.me</div>
      <div class="motto">這個世界的異鄉人</div>
      <post-list></post-list>
    </div>
  </div>
</template>

<script>
import PostList from '~/components/PostList'
export default {
  components: {
    'post-list': PostList
  },
  layout: 'content'
}
</script>

<style lang="less" scoped>
.container {
  display: flex;
  align-items: center;
  height: 100vh;

  .container-h {
    display: flex;
    flex-direction: column;
    width: 600px;

    div.logo {
      font-family: 'OCR-A';
      font-size: 48px;
      color: #222;
      letter-spacing: -2px;
    }

    div.motto {
      font-size: 20px;
      color: #666;
      letter-spacing: 3px;
    }
  }
}
</style>
