// packages/web-main/components/PostEditor.tsx
import React from 'react'
import styled from 'styled-components'
import { Dropdown, Button, Icon } from 'antd'
const Container = styled.div`
  display: flex;
  flex-direction: column;
  height: 100%;
`

const TitleBar = styled.div`
  display: flex;
  border-bottom: 1px solid #dcdcdc;
  align-items: center;
  width: 100%;
  height: 54px;
  padding-left: 20px;
`

const TitleInput = styled.input`
  font-size: 24px;
  line-height: 1;
  width: 100%;
  display: block;
  outline: none;
  border: none;

  &::placeholder {
    opacity: 0.6;
  }
`

const TypeBar = styled.div`
  flex-shrink: 1;
  border-left: 1px dashed #dedede;
  padding-left: 20px;
  padding-right: 20px;
`
const PostEditor: React.FC = () => {
  return (
    <Container>
      <TitleBar>
        <TitleInput placeholder="在此输入标题..." />
        <TypeBar>
          <Dropdown overlay={<div>2</div>}>
            <Button>
              Button <Icon type="down" />
            </Button>
          </Dropdown>
        </TypeBar>
      </TitleBar>
    </Container>
  )
}

export default PostEditor

// src/web.mce/components/admin/posts/PostEditor.vue
<template>
  <section class="container">
    <section class="title">
      <input class="input-title" placeholder="来个标题吧" type="text" v-model="qTitle">
    </section>
    <section class="content">
      <div class="quill-editor"
        :content="qContent"
        @change="onEditorChange($event)"
        v-quill="editorOption">
      </div>
    </section>
    <section class="footer">
      <a-button type="primary" class="tool-button" @click="() => save(false)">发布</a-button>
      <a-button class="tool-button" @click="() => save(true)">保存为草稿</a-button>
    </section>
  </section>
</template>

<script>
import { Button } from 'ant-design-vue'

export default {
  name: 'PostEditor',
  components: {
    [Button.name]: Button,
  },
  props: {
    title: {
      type: String,
    },
    content: {
      type: String,
    }
  },
  data () {
    return {
      qTitle: this.title,
      qContent: this.content,
      editorOption: {
        // some quill options
        placeholder: '写点什么吧...',
        modules: {
          toolbar: [
            [{ 'font': [] }],
            ['bold', 'italic', 'underline', 'strike'],
            ['blockquote', 'code-block'],
            [{ 'align': [] }],
            [{ 'color': [] }, { 'background': [] }],
          ]
        }
      }
    }
  },
  methods: {
    onEditorChange({ html }) {
      this.qContent = html
    },
    // emit 'save' event
    // data: {
    //   "title": <title>,
    //   "content": <content>
    //}
    save(isDraft) {
      const resultData = {
        title: this.qTitle,
        content: this.qContent,
        isDraft,
      }

      this.$emit('save', resultData)
    },

  }
}
</script>

<style lang="less">
// quill editor global style
// remove quill editor's border

@containerFont: 16px;
.ql-snow {
  &.ql-toolbar,
  &.ql-container {
    border: none !important;
    font-size: 15px;
  }

  &.ql-container {
    font-size: @containerFont;
    line-height: 1.5;

    p {
      margin-bottom:  1.2 * @containerFont;
    }
  }
}
</style>

<style lang="less" scoped>
.container {
  display: flex;
  flex: 1;
  flex-direction: column;
  overflow-y: hidden;
  height: 100%;

  .title {
    border-bottom: 1px solid #dcdcdc;
    padding-bottom: 1.5rem;
    margin-bottom: 0.5rem;

    .input-title {
      font-size: 24px;
      line-height: 1;
      width: 100%;
      display: block;
      outline: none;
      border: none;

      &::placeholder{
        opacity: 0.6;
      }
    }
  }

  .content {
    flex-grow: 2;
  }

  .footer {
    padding-top: 1rem;
    box-shadow: 0 -1px 3px 1px #bebebe70;
    .tool-button {
      margin-right: 1rem;
    }
  }
}
</style>
