// packages/web-main/components/LoginForm.tsx
import React, { useCallback, useState } from 'react'
import { Form, Input, Button, Icon } from 'antd'
import styled from 'styled-components'

// styles
const LoginSuccessBar = styled.div`
  width: 100%;
  background-color: #389e0d;
  color: white;
  height: 30px;
  line-height: 28px;
  font-weight: 400;
  box-shadow: 0 2px 0 rgba(0, 0, 0, 0.045);
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.12);
  text-align: center;
  border-radius: 4px;
`
export interface LoginFormProps {
  onLogin: (input: { name: string; password: string }) => Promise<boolean> // return if success
  form: any
}

const LoginForm: React.FC<LoginFormProps> = props => {
  const { onLogin } = props
  const [isLoading, setLoading] = useState(false)
  const [isLoginSuccess, setLoginSuccess] = useState(false)

  const { getFieldDecorator, validateFields } = props.form
  const formItemProps = {
    labelCol: { span: 6 },
    wrapperCol: { span: 18 },
  }

  const handleSubmit = useCallback((e: any) => {
    e.preventDefault()
    setLoading(true)
    validateFields(async (err: any, values: any) => {
      if (err) {
        // not handle error first
        setLoading(false)
        return
      }
      const result = await onLogin(values)
      if (result) {
        setLoginSuccess(true)
      } else {
        setLoading(false)
      }
    })
  }, [])
  return (
    <Form
      layout="horizontal"
      labelAlign="right"
      style={{ width: '100%' }}
      onSubmit={handleSubmit}
    >
      <Form.Item label="username:" {...formItemProps}>
        {getFieldDecorator('name', {
          rules: [{ required: true, message: 'username is required' }],
        })(<Input />)}
      </Form.Item>
      <Form.Item label="password" {...formItemProps}>
        {getFieldDecorator('password', {
          rules: [{ required: true, message: 'password is required' }],
        })(<Input type="password" />)}
      </Form.Item>

      <Form.Item>
        {isLoginSuccess ? (
          <LoginSuccessBar>
            <Icon type="check" />
            <span style={{ marginLeft: '6px' }}>Success</span>
          </LoginSuccessBar>
        ) : isLoading ? (
          <Button loading type="primary" style={{ width: '100%' }}>
            <span>Loading</span>
          </Button>
        ) : (
          <Button type="primary" htmlType="submit" style={{ width: '100%' }}>
            Login
          </Button>
        )}
      </Form.Item>
    </Form>
  )
}

const WLoginForm = Form.create<LoginFormProps>({
  name: 'login_form',
})(LoginForm)

export default WLoginForm

// src/web.mce/components/admin/LoginForm.vue
<template>
  <div class="form">
    <a-form layout="horizontal" class="login-form"
      @submit="handleSubmit"
      :autoFormCreate="(form) => {this.form = form}">

      <a-form-item>
        <div class="title">Admin Login</div>
      </a-form-item>
      <a-form-item
        fieldDecoratorId="username"
        :fieldDecoratorOptions="{ rules: [{ required: true, message: 'Please input your username!' }]}">
        <a-input
          size="large"
          placeholder="UserName"
          ref="usernameInput"
          v-model="usernameContent">
          <a-icon slot="prefix" type="user" />
          <a-icon v-if="usernameContent" slot="suffix" type="close-circle" @click="clearUsernameContent" />
        </a-input>
      </a-form-item>
      <a-form-item
        fieldDecoratorId="password">
        <a-input
          size="large"
          placeholder="PassWord"
          type="password"
          ref="passowrdInput"
          v-model="passwordContent">
          <a-icon slot="prefix" type="lock" />
          <a-icon v-if="passwordContent" slot="suffix" type="close-circle" @click="clearPasswordContent"/>
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-button v-if="!loginPending" type="primary" class="login-form-button" size="large"
          htmlType="submit">
          Login
        </a-button>
        <a-button v-else type="primary" class="login-form-button" size="large" disabled>
          <a-icon type="loading"/> Login
        </a-button>
      </a-form-item>
    </a-form>
  </div>
</template>

<script>
import { Button, Form, Input, Icon } from 'ant-design-vue'
import authService from '~/services/auth'
const { Item } = Form

export default {
  components: {
    [Button.name]: Button,
    [Form.name]: Form,
    [Item.name]: Item,
    [Icon.name]: Icon,
    [Input.name]: Input,
  },
  props: {
    loginPending: {
      type: Boolean,
      required: true,
      default: false,
    },
  },
  data() {
    return {
      usernameContent: '',
      passwordContent: ''
    }
  },
  methods: {
    clearUsernameContent() {
      this.$refs.usernameInput.focus()
      this.usernameContent = ''
      this.form.setFieldsValue({username: ''})

    },
    clearPasswordContent() {
      this.$refs.passowrdInput.focus()
      this.passwordContent = ''
      this.form.setFieldsValue({password: ''})
    },
    async handleSubmit(e) {
      e.preventDefault()
      const { username, password } = this.form.getFieldsValue()
      // emit event
      this.$emit('submit', {
        username,
        password
      })
    }
  },
}

</script>

<style lang="less" scoped>

.form {
  display: flex;
  min-height: 300px;
  width: 420px;
  background-color: white;
  box-shadow: 0 0 8px 1px rgba(150, 150, 150, 0.2);
  padding: 1rem 2rem;

  .title {
    font-size: 22px;
    text-align: center;
  }

  .login-form {
    width: 100%;
  }

  .login-form-button {
    width: 100%;
  }
}
</style>
